#[theme]
#primaryColor="#5681d0"
#backgroundColor="#1e481d"
#secondaryBackgroundColor="#1e3416"
#textColor="#f8f8f2"


[theme]
primaryColor="#5681d0"
backgroundColor="#212750"
secondaryBackgroundColor="#1a1a3d"
textColor="#f8f8f2"